name: XBO.io
favicon: null
layout_spectrum: 0.62735
typography_spectrum: 0.14799
title: XBOX News and much more
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-20866705-9
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#127e11'
    - '#ffffff'
    - '#c9c9cb'
    - '#53b520'
    - '#70ae6d'
  brandStrength: 0
  lightness: 0.22233239142224193
  saturation: 1
  rhythmicContrast: 0.942206951091066
purpose: []
